name: Unit Test
on: [push]
jobs:
  unit-test:
    strategy:
      matrix:
        go-version: [1.20.x]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Setup Go
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go-version }}
    
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Generate coverage report
      run: |
        go test -coverprofile cover.out ./
    
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        directory: ./
        files: cover.out
        fail_ci_if_error: true
        flags: unittests
        name: codecov-umbrella
        verbose: true